### PR TITLE
resolve #116

### LINKED ISSUE #116: Incorrect Placement of frames when frame array changes size post mount
Changing the frame array's size post `componentDidMount`'s execution the frames get placed incorrectly. If you increase the number of frames, the newly introduced frames get placed behind the frame currently at the center of the carousel, while lowering the number of frames might result in a blank carousel. 

I've made a custom repo demo-ing this bug [here](https://github.com/lluisrojass/re-carousel-frame-bug).

### PR DESCRIPTION
**Pull request by lluisrojass**
Resolves #116 

`componentWillReceiveProps` will now reset frames to default state upon receiving an array of frames differing from `state` frames.

### CODE REVIEW

**Comment by amio** [comment]
Since `componentWillReceiveProps` has been [marked as deprecated](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html), I think we may better handle this in `componentDidUpdate` or `getDerivedStateFromProps`.

File: src/carousel.js [hunk 1]
```diff
@@ -57,9 +53,28 @@ class Carousel extends React.Component {
     this.refs.wrapper.removeEventListener('touchend', this.onTouchEnd, {capture: true})
   }
 
-  componentWillReceiveProps(nextProps) {
+  componentDidUpdate(_, prevState) {
+    if (this.state.frames.length && this.state.frames.length !== prevState.frames.length) {
+      // reset to default state
+      this.hideFrames()
+      translateXY(this.refs['f0'], 0, 0, 0)
```
Comment (amio) [inline src/carousel.js]: Should use `this.prepareAutoSlide()` instead of `translateXY(this.refs['f0'], 0, 0, 0)` to get all frames positioned correctly.

File: src/carousel.js [hunk 2]
```diff
@@ -57,9 +53,28 @@ class Carousel extends React.Component {
...
+  }
+
+  static getDerivedStateFromProps(nextProps, prevState) {
     const frames = [].concat(nextProps.frames || nextProps.children || [])
-    this.setState({ frames })
+    const nextState = { frames } 
+    if (frames.length && frames.length !== prevState.frames.length) {
+      nextState.current = 0
+    }
+
```
Comment (amio) [inline src/carousel.js]: Extra spaces

Comment (lluisrojass) [reply src/carousel.js]: got it 👍

File: src/carousel.js (hunk 1 above)
Comment (lluisrojass) [reply src/carousel.js]: @amio  just noticed the comments :/ will be able to get to it within 24 hours, thanks for the patience and I apologize for the latency.

Comment (lluisrojass) [reply src/carousel.js]: @amio this has been addressed

File: src/carousel.js (hunk 2 above)
Comment (lluisrojass) [reply src/carousel.js]: @amio  this has been addressed in latest commit.
